a<-function(b){
  x<-0
  y<-2
  while(x<b){
    y<-y+1
  }
  if(y%%2!=0){
    if(y%%3!=0){
      if(y%%4!=0){
        if(y%%5!=0){
          if(y%%6!=0){
            if(y%%7!=0){
              if(y%%8!=0){
                if(y%%9!=0){
                  print(y)
                  x<-x+1
                }
              }
            }
          }
        }
      }
    }
  }
}
a(11)